### ISSUE TITLE
Kiinnostava modi-idea

### ISSUE THREAD

**Issue by AceHanded** [MisterVaTu/Finnishtranslation#1]
Vielä ideaa kiinnostavampi on tekemäni modi-ikoni (eli icon.png -tiedosto), jonka lisäksi on pakko pohtia mitä muuta omasta modistani on "lainattu", vieläpä ilman krediittiä.

Pyydän siis, että mainitset modisivulla käyttäneesi osia omasta modistani. Pyydän myös, että vaihdat modi-ikonin omaan luomukseesi, millainen se sitten onkaan.

-- AceHanded

**Comment by MisterVaTu** [comment]
Hei!

Anteeksi että olen käyttänyt sinun png:tä Korvaan kuvakkeen heti, kun
kerkiän. Lisään myös maininnan että versioissa on käytetty sinun png:tä.

Btw. Niitä sinun tiedostoja ei laiteta juuri tiedostoihin, vaan FI-fi
kansioon, jonka modisi luo. Yritin saada tätä toimimaan automaattisesti,
mutta se ei ole mahdollista.

ma 25. jouluk. 2023 klo 21.38 Vili Könönen ***@***.***>
kirjoitti:

**Comment by AceHanded** [comment]
Hei!

Kiitän ymmärtäväisyydestäsi. Mitä tulee tuohon juurikansiojuttuun, niin yritin viitata sillä siihen, että modin asentaminen / päivittäminen vaatii vain modin zip-tiedoston sisältämän BepInEx-kansion siirtämisen Lethal Company -kansioon, mutta kenties sen voisi esittää paremmallakin tavalla.

-- AceHanded
